table dCalendario
	lineageTag: f7747c2e-de6c-4493-a803-127027c78102

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4c56f2f8-2167-4b0a-ac2c-d3a6671a6d36
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 3a279501-f95c-482c-b5d8-f2c1d8166d8e
			defaultHierarchy: LocalDateTable_e2a55883-9ec5-44a4-a172-816810609142.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 419d3efd-c7b9-4b0a-85b2-70d0b47dbb98
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column NomeMes
		dataType: string
		lineageTag: 675447b6-6f67-4c13-8007-c1ffa00e125b
		summarizeBy: none
		sourceColumn: NomeMes

		annotation SummarizationSetBy = Automatic

	column MesAbre
		dataType: string
		lineageTag: 6cca0355-7323-4d84-9ac4-cdc1a931617c
		summarizeBy: none
		sourceColumn: MesAbre

		annotation SummarizationSetBy = Automatic

	column MesAno
		dataType: string
		lineageTag: 0e84ffde-b3ab-4ffa-94a8-dd35ec5062ea
		summarizeBy: none
		sourceColumn: MesAno

		annotation SummarizationSetBy = Automatic

	column MesNum
		dataType: double
		lineageTag: dbed43df-a80e-4005-9f45-1bdd0e17bc0c
		summarizeBy: sum
		sourceColumn: MesNum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnoMesINT
		dataType: double
		lineageTag: 913cfd48-8ccc-47ab-ade8-276745e1aceb
		summarizeBy: sum
		sourceColumn: AnoMesINT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InicioMes
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8186bf01-1d5c-417e-87a1-136b32fbb6c2
		summarizeBy: none
		sourceColumn: InicioMes

		variation Variation
			isDefault
			relationship: 13c05f65-7ff6-4364-b3fd-aa93e38c6783
			defaultHierarchy: LocalDateTable_f8625c3a-51a5-49e5-835e-57b071a58d52.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: d386be25-8c01-4c91-8a5c-5c074d85647e
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column TrimestreAbreviado
		dataType: string
		lineageTag: 29965ce9-c3ab-4bf2-a2ba-a4805f5cf2e0
		summarizeBy: none
		sourceColumn: TrimestreAbreviado

		annotation SummarizationSetBy = Automatic

	column Bimestre
		dataType: string
		lineageTag: d29760f1-a71a-4cc2-8858-4d55a032ead0
		summarizeBy: none
		sourceColumn: Bimestre

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: a0c07566-239e-4b31-80d5-41365e267db4
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: f68fe0b7-409c-4ae2-b606-a79684c0b1ea
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column DiaSemana
		dataType: int64
		formatString: 0
		lineageTag: 9dd2344d-65fb-494c-8ad7-64d22700024f
		summarizeBy: sum
		sourceColumn: DiaSemana

		annotation SummarizationSetBy = Automatic

	column NomeDia
		dataType: string
		lineageTag: 7cefb5bf-04e0-43e6-8504-feeda2d64a50
		summarizeBy: none
		sourceColumn: NomeDia

		annotation SummarizationSetBy = Automatic

	column dataPassada?
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 510a4f2c-f958-424e-8b8f-96e21c14d936
		summarizeBy: none
		sourceColumn: dataPassada?

		annotation SummarizationSetBy = Automatic

	column AnoAtual
		dataType: string
		lineageTag: ff5728cf-e835-48eb-b239-4c977c118229
		summarizeBy: none
		sourceColumn: AnoAtual

		annotation SummarizationSetBy = Automatic

	column MesAtual
		dataType: string
		lineageTag: e95d2b34-6677-4b84-97c4-1afe9787eb26
		summarizeBy: none
		sourceColumn: MesAtual

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		queryGroup: dimensao
		source = ```
				let
				
				//Alterar somente a Tabela e a coluna de datas
				/* A Tabela é onde possui uma coluna Data que deseja usar em seus cálculos ou visuais. 
				Exemplo. Tabela fVendas que possui a coluna Data Pedido Ficaria List.Min (fVendas[Data Pedido]).
				Se Possuir mais de uma coluna ficaria List.Min (fVendas[Data Pedido] & fVendas[Data Vencimento]).
				*/
				
				    MenorData = List.Min (fLancamentos[competencia_data]),
				    MaiorData = List.Max (fLancamentos[competencia_data]),
					
				//Não alterar daqui pra baixo	
					
				    DataInicio = Date.StartOfYear(MenorData),
				    DataFim = Date.EndOfYear(MaiorData),
				    Dias = Duration.Days(DataFim- DataInicio) +1,
				    ListarDatas = List.Dates(DataInicio, Dias, #duration(1,0,0,0)),
				    Tabela = #table(
				        type table[
				            Data = date,
				            Ano = Int64.Type,
				            NomeMes = text,
				            MesAbre = text,
				            MesAno = text,
				            MesNum = number,
				            AnoMesINT = number,
				            InicioMes = date,
				            Trimestre = Int64.Type,
				            TrimestreAbreviado = text,
				            Bimestre = text,
				            Semestre = text,
				            Semana = Int64.Type,
				            DiaSemana = Int64.Type,
				            NomeDia = text,
				            Passado = logical,
				            AnoAtual = text,
				            MesAtual = text
				        ],
				        List.Transform(
				            ListarDatas,
				            each {
				                _,
				                Date.Year(_),
				                Text.Proper( Date.MonthName(_)),
				                Text.Proper(Text.Start(Date.MonthName(_), 3)),
				                Text.Proper(Text.Start(Date.MonthName(_), 3)) & "-" & Text.End(Text.From(Date.Year(_)), 2),
				                Date.Month(_),
				                Date.Year(_) * 100 + Date.Month(_),
				                Date.StartOfMonth(_),
				                Date.QuarterOfYear(_),
				                Text.From(Date.QuarterOfYear(_)) & "º Trim ",
				                Text.From( Number.RoundUp( Date.Month(_)/2,0)) & "º Bim",
				                Text.From( Number.RoundUp( Date.Month(_)/6,0)) & "º Sem",
				                Date.WeekOfMonth(_),
				                Date.DayOfWeek(_),
				                Date.DayOfWeekName(_),
				                if _ <= MaiorData then true else false,
				                if Date.IsInCurrentYear(_) then "Ano Atual" else Text.From(Date.Year(_)),
				                if Date.IsInCurrentYear(_) and Date.IsInCurrentMonth(_) then "Mês Atual" else Text.Proper( Date.MonthName(_))
				            }
				
				        )
				    ),
				    #"Colunas Renomeadas" = Table.RenameColumns(Tabela,{{"Passado", "dataPassada?"}})
				in
				    #"Colunas Renomeadas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

