table dEstruturaDRE
	lineageTag: ad782d2d-3449-49f6-8e16-09762b39a6dd

	column id
		dataType: string
		lineageTag: a8f55bd5-677c-4b3c-a86d-3b913540bd5c
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column index
		dataType: int64
		formatString: 0
		lineageTag: b635a5e8-d988-41f9-b837-721b982253ba
		summarizeBy: none
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	column contaGerencial
		dataType: string
		lineageTag: 2969415a-7530-4b50-9cfe-0ee12bd78aa0
		summarizeBy: none
		sourceColumn: contaGerencial

		annotation SummarizationSetBy = Automatic

	column subtotal
		dataType: int64
		formatString: 0
		lineageTag: 7d22e8ab-af3b-464c-a4a9-b8268a2809dc
		summarizeBy: none
		sourceColumn: subtotal

		annotation SummarizationSetBy = Automatic

	column empresa
		dataType: string
		lineageTag: caa4c294-670e-4cb4-9460-6de492466c9f
		summarizeBy: none
		sourceColumn: empresa

		annotation SummarizationSetBy = Automatic

	partition dEstruturaDRE = m
		mode: import
		queryGroup: dimensao
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Meu Computador\OneDrive\Estudos\Tecnologia\Xperiun\Dashboard de Controladoria com DRE\Desafio\BaseDados.xlsx"), null, true),
				    dEstruturaDRE_Sheet = Fonte{[Item="dEstruturaDRE",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(dEstruturaDRE_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id", Int64.Type}, {"index", Int64.Type}, {"contaGerencial", type text}, {"subtotal", Int64.Type}, {"empresa", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [id] <> null and [id] <> ""),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"id", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

