table fLancamentos
	lineageTag: a39f551d-65fc-4f02-bee7-23a36947e618

	column competencia_data
		dataType: dateTime
		formatString: Long Date
		lineageTag: c55861e8-8e6b-4bc3-9eae-90dd9344033a
		summarizeBy: none
		sourceColumn: competencia_data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column planoContas_id
		dataType: string
		lineageTag: 29adef35-5377-4f72-ae68-993095f5766c
		summarizeBy: none
		sourceColumn: planoContas_id

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 9a995cc3-7a6f-4e7d-8d4f-53b94bd28ed3
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition fLancamentos = m
		mode: import
		queryGroup: fato
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(diretorioDados), true, true),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each Text.StartsWith([Name], "fLan")),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Filtradas",{"Data"}),
				    #"Data Expandido" = Table.ExpandTableColumn(#"Outras Colunas Removidas", "Data", {"competencia_data", "planoContas_id", "valor"}, {"Data.competencia_data", "Data.planoContas_id", "Data.valor"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Data Expandido", each [Data.competencia_data] <> null and [Data.competencia_data] <> ""),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Filtradas1",{{"Data.competencia_data", type date}, {"Data.planoContas_id", type text}, {"Data.valor", Currency.Type}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Data.competencia_data", "competencia_data"}, {"Data.planoContas_id", "planoContas_id"}, {"Data.valor", "valor"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

