table fOrcamento
	lineageTag: a410ce02-0376-4278-af24-5db4b6e2f387

	column competencia_data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9cb156c3-ae94-4c02-a514-b9b22993c6b2
		summarizeBy: none
		sourceColumn: competencia_data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column planoContas_id
		dataType: string
		lineageTag: b3dbc72b-a11f-41d3-948b-58e4041fd90c
		summarizeBy: none
		sourceColumn: planoContas_id

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: decimal
		lineageTag: 52b9bb0b-45f0-48e9-a29b-e9a49e1218d7
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column4
		dataType: string
		lineageTag: 22c636ff-7110-43c7-8536-99dd63c15ffd
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 0f1d69ba-4c1d-4b7e-8297-fd00837b1fb8
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	partition fOrcamento = m
		mode: import
		queryGroup: fato
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(diretorioDados), null, true),
				    fOrcamento_Sheet = Fonte{[Item="fOrcamento",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(fOrcamento_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"competencia_data", type date}, {"planoContas_id", type text}, {"valor", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

